//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;



namespace Config
{ 
public partial class Tables
{
    public item.TbItem TbItem {get; }
    public character.TbCharacter TbCharacter {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        var tables = new System.Collections.Generic.Dictionary<string, object>();
        TbItem = new item.TbItem(loader("item_tbitem")); 
        tables.Add("item.TbItem", TbItem);
        TbCharacter = new character.TbCharacter(loader("character_tbcharacter")); 
        tables.Add("character.TbCharacter", TbCharacter);

        PostInit();
        TbItem.Resolve(tables); 
        TbCharacter.Resolve(tables); 
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        TbItem.TranslateText(translator); 
        TbCharacter.TranslateText(translator); 
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}