// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: BoneProto.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from BoneProto.proto</summary>
public static partial class BoneProtoReflection {

  #region Descriptor
  /// <summary>File descriptor for BoneProto.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static BoneProtoReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg9Cb25lUHJvdG8ucHJvdG8aEU9wdGlvbk1zZ0lkLnByb3RvIlQKCEJvbmVO",
          "b3RlEg4KBm5vdGVJZBgBIAEoBRIRCglub3RlVGl0bGUYAiABKAkSEwoLbm90",
          "ZWNvbnRlbnQYAyABKAkSEAoIaW1hZ2V1cmwYBCADKAkiJQoNQ1NCb25lUmVx",
          "dWVzdBIOCgZib25lSWQYASABKAU6BMA+kE4itgEKDlNDQm9uZVJlc3BvbnNl",
          "Eg4KBnJlc3VsdBgBIAEoBRIOCgZib25lSWQYAiABKAUSDAoEdHlwZRgDIAEo",
          "CRIQCghwb3NpdGlvbhgEIAEoCRIQCghib25lbmFtZRgFIAEoCRIQCghib25l",
          "dGlsZRgGIAEoCRITCgtib25lY29udGVudBgHIAEoCRIcCgRub3RlGAggASgL",
          "MgkuQm9uZU5vdGVIAIgBAToEwD6RTkIHCgVfbm90ZWIGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::OptionMsgIdReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::BoneNote), global::BoneNote.Parser, new[]{ "NoteId", "NoteTitle", "Notecontent", "Imageurl" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::CSBoneRequest), global::CSBoneRequest.Parser, new[]{ "BoneId" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::SCBoneResponse), global::SCBoneResponse.Parser, new[]{ "Result", "BoneId", "Type", "Position", "Bonename", "Bonetile", "Bonecontent", "Note" }, new[]{ "Note" }, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class BoneNote : pb::IMessage<BoneNote>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<BoneNote> _parser = new pb::MessageParser<BoneNote>(() => new BoneNote());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<BoneNote> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::BoneProtoReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public BoneNote() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public BoneNote(BoneNote other) : this() {
    noteId_ = other.noteId_;
    noteTitle_ = other.noteTitle_;
    notecontent_ = other.notecontent_;
    imageurl_ = other.imageurl_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public BoneNote Clone() {
    return new BoneNote(this);
  }

  /// <summary>Field number for the "noteId" field.</summary>
  public const int NoteIdFieldNumber = 1;
  private int noteId_;
  /// <summary>
  ///笔记id
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int NoteId {
    get { return noteId_; }
    set {
      noteId_ = value;
    }
  }

  /// <summary>Field number for the "noteTitle" field.</summary>
  public const int NoteTitleFieldNumber = 2;
  private string noteTitle_ = "";
  /// <summary>
  ///笔记标题
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string NoteTitle {
    get { return noteTitle_; }
    set {
      noteTitle_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "notecontent" field.</summary>
  public const int NotecontentFieldNumber = 3;
  private string notecontent_ = "";
  /// <summary>
  ///笔记内容
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Notecontent {
    get { return notecontent_; }
    set {
      notecontent_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "imageurl" field.</summary>
  public const int ImageurlFieldNumber = 4;
  private static readonly pb::FieldCodec<string> _repeated_imageurl_codec
      = pb::FieldCodec.ForString(34);
  private readonly pbc::RepeatedField<string> imageurl_ = new pbc::RepeatedField<string>();
  /// <summary>
  ///笔记图片地址
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<string> Imageurl {
    get { return imageurl_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as BoneNote);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(BoneNote other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (NoteId != other.NoteId) return false;
    if (NoteTitle != other.NoteTitle) return false;
    if (Notecontent != other.Notecontent) return false;
    if(!imageurl_.Equals(other.imageurl_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (NoteId != 0) hash ^= NoteId.GetHashCode();
    if (NoteTitle.Length != 0) hash ^= NoteTitle.GetHashCode();
    if (Notecontent.Length != 0) hash ^= Notecontent.GetHashCode();
    hash ^= imageurl_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (NoteId != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(NoteId);
    }
    if (NoteTitle.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(NoteTitle);
    }
    if (Notecontent.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Notecontent);
    }
    imageurl_.WriteTo(output, _repeated_imageurl_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (NoteId != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(NoteId);
    }
    if (NoteTitle.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(NoteTitle);
    }
    if (Notecontent.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Notecontent);
    }
    imageurl_.WriteTo(ref output, _repeated_imageurl_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (NoteId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(NoteId);
    }
    if (NoteTitle.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(NoteTitle);
    }
    if (Notecontent.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Notecontent);
    }
    size += imageurl_.CalculateSize(_repeated_imageurl_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(BoneNote other) {
    if (other == null) {
      return;
    }
    if (other.NoteId != 0) {
      NoteId = other.NoteId;
    }
    if (other.NoteTitle.Length != 0) {
      NoteTitle = other.NoteTitle;
    }
    if (other.Notecontent.Length != 0) {
      Notecontent = other.Notecontent;
    }
    imageurl_.Add(other.imageurl_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          NoteId = input.ReadInt32();
          break;
        }
        case 18: {
          NoteTitle = input.ReadString();
          break;
        }
        case 26: {
          Notecontent = input.ReadString();
          break;
        }
        case 34: {
          imageurl_.AddEntriesFrom(input, _repeated_imageurl_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          NoteId = input.ReadInt32();
          break;
        }
        case 18: {
          NoteTitle = input.ReadString();
          break;
        }
        case 26: {
          Notecontent = input.ReadString();
          break;
        }
        case 34: {
          imageurl_.AddEntriesFrom(ref input, _repeated_imageurl_codec);
          break;
        }
      }
    }
  }
  #endif

}

/// <summary>
///骨骼信息请求
/// </summary>
public sealed partial class CSBoneRequest : pb::IMessage<CSBoneRequest>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<CSBoneRequest> _parser = new pb::MessageParser<CSBoneRequest>(() => new CSBoneRequest());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<CSBoneRequest> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::BoneProtoReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public CSBoneRequest() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public CSBoneRequest(CSBoneRequest other) : this() {
    boneId_ = other.boneId_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public CSBoneRequest Clone() {
    return new CSBoneRequest(this);
  }

  /// <summary>Field number for the "boneId" field.</summary>
  public const int BoneIdFieldNumber = 1;
  private int boneId_;
  /// <summary>
  ///骨骼id
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int BoneId {
    get { return boneId_; }
    set {
      boneId_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as CSBoneRequest);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(CSBoneRequest other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (BoneId != other.BoneId) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (BoneId != 0) hash ^= BoneId.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (BoneId != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(BoneId);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (BoneId != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(BoneId);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (BoneId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(BoneId);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(CSBoneRequest other) {
    if (other == null) {
      return;
    }
    if (other.BoneId != 0) {
      BoneId = other.BoneId;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          BoneId = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          BoneId = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

/// <summary>
///骨骼信息返回
/// </summary>
public sealed partial class SCBoneResponse : pb::IMessage<SCBoneResponse>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<SCBoneResponse> _parser = new pb::MessageParser<SCBoneResponse>(() => new SCBoneResponse());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<SCBoneResponse> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::BoneProtoReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public SCBoneResponse() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public SCBoneResponse(SCBoneResponse other) : this() {
    result_ = other.result_;
    boneId_ = other.boneId_;
    type_ = other.type_;
    position_ = other.position_;
    bonename_ = other.bonename_;
    bonetile_ = other.bonetile_;
    bonecontent_ = other.bonecontent_;
    note_ = other.note_ != null ? other.note_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public SCBoneResponse Clone() {
    return new SCBoneResponse(this);
  }

  /// <summary>Field number for the "result" field.</summary>
  public const int ResultFieldNumber = 1;
  private int result_;
  /// <summary>
  ///结果 1成功 0失败  
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Result {
    get { return result_; }
    set {
      result_ = value;
    }
  }

  /// <summary>Field number for the "boneId" field.</summary>
  public const int BoneIdFieldNumber = 2;
  private int boneId_;
  /// <summary>
  ///骨骼id
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int BoneId {
    get { return boneId_; }
    set {
      boneId_ = value;
    }
  }

  /// <summary>Field number for the "type" field.</summary>
  public const int TypeFieldNumber = 3;
  private string type_ = "";
  /// <summary>
  ///类型
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Type {
    get { return type_; }
    set {
      type_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "position" field.</summary>
  public const int PositionFieldNumber = 4;
  private string position_ = "";
  /// <summary>
  ///所属部位
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Position {
    get { return position_; }
    set {
      position_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "bonename" field.</summary>
  public const int BonenameFieldNumber = 5;
  private string bonename_ = "";
  /// <summary>
  ///骨骼名称
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Bonename {
    get { return bonename_; }
    set {
      bonename_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "bonetile" field.</summary>
  public const int BonetileFieldNumber = 6;
  private string bonetile_ = "";
  /// <summary>
  ///骨骼标题
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Bonetile {
    get { return bonetile_; }
    set {
      bonetile_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "bonecontent" field.</summary>
  public const int BonecontentFieldNumber = 7;
  private string bonecontent_ = "";
  /// <summary>
  ///骨骼内容
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Bonecontent {
    get { return bonecontent_; }
    set {
      bonecontent_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "note" field.</summary>
  public const int NoteFieldNumber = 8;
  private global::BoneNote note_;
  /// <summary>
  ///笔记内容
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::BoneNote Note {
    get { return note_; }
    set {
      note_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as SCBoneResponse);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(SCBoneResponse other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Result != other.Result) return false;
    if (BoneId != other.BoneId) return false;
    if (Type != other.Type) return false;
    if (Position != other.Position) return false;
    if (Bonename != other.Bonename) return false;
    if (Bonetile != other.Bonetile) return false;
    if (Bonecontent != other.Bonecontent) return false;
    if (!object.Equals(Note, other.Note)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Result != 0) hash ^= Result.GetHashCode();
    if (BoneId != 0) hash ^= BoneId.GetHashCode();
    if (Type.Length != 0) hash ^= Type.GetHashCode();
    if (Position.Length != 0) hash ^= Position.GetHashCode();
    if (Bonename.Length != 0) hash ^= Bonename.GetHashCode();
    if (Bonetile.Length != 0) hash ^= Bonetile.GetHashCode();
    if (Bonecontent.Length != 0) hash ^= Bonecontent.GetHashCode();
    if (note_ != null) hash ^= Note.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Result != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Result);
    }
    if (BoneId != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(BoneId);
    }
    if (Type.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Type);
    }
    if (Position.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(Position);
    }
    if (Bonename.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(Bonename);
    }
    if (Bonetile.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(Bonetile);
    }
    if (Bonecontent.Length != 0) {
      output.WriteRawTag(58);
      output.WriteString(Bonecontent);
    }
    if (note_ != null) {
      output.WriteRawTag(66);
      output.WriteMessage(Note);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Result != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Result);
    }
    if (BoneId != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(BoneId);
    }
    if (Type.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Type);
    }
    if (Position.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(Position);
    }
    if (Bonename.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(Bonename);
    }
    if (Bonetile.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(Bonetile);
    }
    if (Bonecontent.Length != 0) {
      output.WriteRawTag(58);
      output.WriteString(Bonecontent);
    }
    if (note_ != null) {
      output.WriteRawTag(66);
      output.WriteMessage(Note);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Result != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Result);
    }
    if (BoneId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(BoneId);
    }
    if (Type.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Type);
    }
    if (Position.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Position);
    }
    if (Bonename.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Bonename);
    }
    if (Bonetile.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Bonetile);
    }
    if (Bonecontent.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Bonecontent);
    }
    if (note_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Note);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(SCBoneResponse other) {
    if (other == null) {
      return;
    }
    if (other.Result != 0) {
      Result = other.Result;
    }
    if (other.BoneId != 0) {
      BoneId = other.BoneId;
    }
    if (other.Type.Length != 0) {
      Type = other.Type;
    }
    if (other.Position.Length != 0) {
      Position = other.Position;
    }
    if (other.Bonename.Length != 0) {
      Bonename = other.Bonename;
    }
    if (other.Bonetile.Length != 0) {
      Bonetile = other.Bonetile;
    }
    if (other.Bonecontent.Length != 0) {
      Bonecontent = other.Bonecontent;
    }
    if (other.note_ != null) {
      if (note_ == null) {
        Note = new global::BoneNote();
      }
      Note.MergeFrom(other.Note);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Result = input.ReadInt32();
          break;
        }
        case 16: {
          BoneId = input.ReadInt32();
          break;
        }
        case 26: {
          Type = input.ReadString();
          break;
        }
        case 34: {
          Position = input.ReadString();
          break;
        }
        case 42: {
          Bonename = input.ReadString();
          break;
        }
        case 50: {
          Bonetile = input.ReadString();
          break;
        }
        case 58: {
          Bonecontent = input.ReadString();
          break;
        }
        case 66: {
          if (note_ == null) {
            Note = new global::BoneNote();
          }
          input.ReadMessage(Note);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Result = input.ReadInt32();
          break;
        }
        case 16: {
          BoneId = input.ReadInt32();
          break;
        }
        case 26: {
          Type = input.ReadString();
          break;
        }
        case 34: {
          Position = input.ReadString();
          break;
        }
        case 42: {
          Bonename = input.ReadString();
          break;
        }
        case 50: {
          Bonetile = input.ReadString();
          break;
        }
        case 58: {
          Bonecontent = input.ReadString();
          break;
        }
        case 66: {
          if (note_ == null) {
            Note = new global::BoneNote();
          }
          input.ReadMessage(Note);
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
