// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: OptionMsgId.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from OptionMsgId.proto</summary>
public static partial class OptionMsgIdReflection {

  #region Descriptor
  /// <summary>File descriptor for OptionMsgId.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static OptionMsgIdReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChFPcHRpb25Nc2dJZC5wcm90bxogZ29vZ2xlL3Byb3RvYnVmL2Rlc2NyaXB0",
          "b3IucHJvdG86LwoFbXNnaWQSHy5nb29nbGUucHJvdG9idWYuTWVzc2FnZU9w",
          "dGlvbnMY6AcgASgFYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::Google.Protobuf.Reflection.DescriptorReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, new pb::Extension[] { OptionMsgIdExtensions.Msgid }, null));
  }
  #endregion

}
/// <summary>Holder for extension identifiers generated from the top level of OptionMsgId.proto</summary>
public static partial class OptionMsgIdExtensions {
  public static readonly pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, int> Msgid =
    new pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, int>(1000, pb::FieldCodec.ForInt32(8000, 0));
}


#endregion Designer generated code
