// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GameRace.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from GameRace.proto</summary>
public static partial class GameRaceReflection {

  #region Descriptor
  /// <summary>File descriptor for GameRace.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static GameRaceReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg5HYW1lUmFjZS5wcm90bxoRT3B0aW9uTXNnSWQucHJvdG8aDU5SZXN1bHQu",
          "cHJvdG8qOAoIR2FtZVJhY2USCQoFSHVtYW4QABIHCgNPcmMQARIKCgZVbmRl",
          "YWQQAhIMCghOaWdodEVsZhADYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::OptionMsgIdReflection.Descriptor, global::NResultReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::GameRace), }, null, null));
  }
  #endregion

}
#region Enums
/// <summary>
///游戏种族
/// </summary>
public enum GameRace {
  [pbr::OriginalName("Human")] Human = 0,
  [pbr::OriginalName("Orc")] Orc = 1,
  [pbr::OriginalName("Undead")] Undead = 2,
  [pbr::OriginalName("NightElf")] NightElf = 3,
}

#endregion


#endregion Designer generated code
