// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: NItem.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from NItem.proto</summary>
public static partial class NItemReflection {

  #region Descriptor
  /// <summary>File descriptor for NItem.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static NItemReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CgtOSXRlbS5wcm90bxoRT3B0aW9uTXNnSWQucHJvdG8aDU5SZXN1bHQucHJv",
          "dG8iOwoFTkl0ZW0SEQoJaXRlbWNmZ2lkGAEgASgDEg8KB2l0ZW1udW0YAiAB",
          "KAUSDgoGaXRlbWlkGAMgASgFYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::OptionMsgIdReflection.Descriptor, global::NResultReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::NItem), global::NItem.Parser, new[]{ "Itemcfgid", "Itemnum", "Itemid" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class NItem : pb::IMessage<NItem>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<NItem> _parser = new pb::MessageParser<NItem>(() => new NItem());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<NItem> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::NItemReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public NItem() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public NItem(NItem other) : this() {
    itemcfgid_ = other.itemcfgid_;
    itemnum_ = other.itemnum_;
    itemid_ = other.itemid_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public NItem Clone() {
    return new NItem(this);
  }

  /// <summary>Field number for the "itemcfgid" field.</summary>
  public const int ItemcfgidFieldNumber = 1;
  private long itemcfgid_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long Itemcfgid {
    get { return itemcfgid_; }
    set {
      itemcfgid_ = value;
    }
  }

  /// <summary>Field number for the "itemnum" field.</summary>
  public const int ItemnumFieldNumber = 2;
  private int itemnum_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Itemnum {
    get { return itemnum_; }
    set {
      itemnum_ = value;
    }
  }

  /// <summary>Field number for the "itemid" field.</summary>
  public const int ItemidFieldNumber = 3;
  private int itemid_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Itemid {
    get { return itemid_; }
    set {
      itemid_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as NItem);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(NItem other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Itemcfgid != other.Itemcfgid) return false;
    if (Itemnum != other.Itemnum) return false;
    if (Itemid != other.Itemid) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Itemcfgid != 0L) hash ^= Itemcfgid.GetHashCode();
    if (Itemnum != 0) hash ^= Itemnum.GetHashCode();
    if (Itemid != 0) hash ^= Itemid.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Itemcfgid != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(Itemcfgid);
    }
    if (Itemnum != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Itemnum);
    }
    if (Itemid != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(Itemid);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Itemcfgid != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(Itemcfgid);
    }
    if (Itemnum != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Itemnum);
    }
    if (Itemid != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(Itemid);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Itemcfgid != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Itemcfgid);
    }
    if (Itemnum != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Itemnum);
    }
    if (Itemid != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Itemid);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(NItem other) {
    if (other == null) {
      return;
    }
    if (other.Itemcfgid != 0L) {
      Itemcfgid = other.Itemcfgid;
    }
    if (other.Itemnum != 0) {
      Itemnum = other.Itemnum;
    }
    if (other.Itemid != 0) {
      Itemid = other.Itemid;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Itemcfgid = input.ReadInt64();
          break;
        }
        case 16: {
          Itemnum = input.ReadInt32();
          break;
        }
        case 24: {
          Itemid = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Itemcfgid = input.ReadInt64();
          break;
        }
        case 16: {
          Itemnum = input.ReadInt32();
          break;
        }
        case 24: {
          Itemid = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
