// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: NResult.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from NResult.proto</summary>
public static partial class NResultReflection {

  #region Descriptor
  /// <summary>File descriptor for NResult.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static NResultReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg1OUmVzdWx0LnByb3RvKiAKB05SZXN1bHQSCwoHU3VjY2VzcxAAEggKBEZh",
          "aWwQAWIGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::NResult), }, null, null));
  }
  #endregion

}
#region Enums
public enum NResult {
  [pbr::OriginalName("Success")] Success = 0,
  [pbr::OriginalName("Fail")] Fail = 1,
}

#endregion


#endregion Designer generated code
