//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace Config.character
{
public sealed partial class Character :  Bright.Config.BeanBase 
{
    public Character(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        Price = _buf.ReadInt();
        UpgradeToItemId = _buf.ReadInt();
        if(_buf.ReadBool()){ ExpireTime = _buf.ReadLong(); } else { ExpireTime = null; }
        BatchUseable = _buf.ReadBool();
        Quality = (character.Ejob)_buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);ExchangeList = new System.Collections.Generic.List<character.CExchange>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { character.CExchange _e0;  _e0 = character.CExchange.DeserializeCExchange(_buf); ExchangeList.Add(_e0);}}
        ExchangeColumn = character.CExchange.DeserializeCExchange(_buf);
        PostInit();
    }

    public static Character DeserializeCharacter(ByteBuf _buf)
    {
        return new character.Character(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 名字
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 描述
    /// </summary>
    public string Desc { get; private set; }
    /// <summary>
    /// 价格
    /// </summary>
    public int Price { get; private set; }
    /// <summary>
    /// 引用当前表
    /// </summary>
    public int UpgradeToItemId { get; private set; }
    public character.Character UpgradeToItemId_Ref { get; private set; }
    /// <summary>
    /// 过期时间
    /// </summary>
    public long? ExpireTime { get; private set; }
    /// <summary>
    /// 能否批量使用
    /// </summary>
    public bool BatchUseable { get; private set; }
    /// <summary>
    /// 品质
    /// </summary>
    public character.Ejob Quality { get; private set; }
    public System.Collections.Generic.List<character.CExchange> ExchangeList { get; private set; }
    /// <summary>
    /// 道具兑换配置
    /// </summary>
    public character.CExchange ExchangeColumn { get; private set; }

    public const int __ID__ = -259077500;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        this.UpgradeToItemId_Ref = (_tables["character.TbCharacter"] as character.TbCharacter).GetOrDefault(UpgradeToItemId);
        foreach(var _e in ExchangeList) { _e?.Resolve(_tables); }
        ExchangeColumn?.Resolve(_tables);
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var _e in ExchangeList) { _e?.TranslateText(translator); }
        ExchangeColumn?.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Desc:" + Desc + ","
        + "Price:" + Price + ","
        + "UpgradeToItemId:" + UpgradeToItemId + ","
        + "ExpireTime:" + ExpireTime + ","
        + "BatchUseable:" + BatchUseable + ","
        + "Quality:" + Quality + ","
        + "ExchangeList:" + Bright.Common.StringUtil.CollectionToString(ExchangeList) + ","
        + "ExchangeColumn:" + ExchangeColumn + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}