//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Config.character
{ 
    public enum Ejob
    {
        /// <summary>
        /// 最差品质
        /// </summary>
        Job1 = 1,
        /// <summary>
        /// 蓝色的
        /// </summary>
        Job2 = 2,
        /// <summary>
        /// 紫色的
        /// </summary>
        Job3 = 3,
        /// <summary>
        /// 最高品质1
        /// </summary>
        Job4 = 4,
        /// <summary>
        /// 最高品质2
        /// </summary>
        Job5 = 5,
        /// <summary>
        /// 最高品质3
        /// </summary>
        Job6 = 6,
    }

} 
