//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace Config.character
{
   
public partial class TbCharacter
{
    private readonly Dictionary<int, character.Character> _dataMap;
    private readonly List<character.Character> _dataList;
    
    public TbCharacter(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, character.Character>();
        _dataList = new List<character.Character>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            character.Character _v;
            _v = character.Character.DeserializeCharacter(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, character.Character> DataMap => _dataMap;
    public List<character.Character> DataList => _dataList;

    public character.Character GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public character.Character Get(int key) => _dataMap[key];
    public character.Character this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}